// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCItoFFzQAibvYssohCZNY-hWwnj4i30XU',
    appId: '1:554364039576:web:ea4658a814a5b4857ffbed',
    messagingSenderId: '554364039576',
    projectId: 'flixflow-2aec5',
    authDomain: 'flixflow-2aec5.firebaseapp.com',
    storageBucket: 'flixflow-2aec5.appspot.com',
    measurementId: 'G-CD3M04Y7QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkQRZsCfu4UduOWNzZRRLG6ekf1zyV5a0',
    appId: '1:554364039576:android:2a9400b9276a89297ffbed',
    messagingSenderId: '554364039576',
    projectId: 'flixflow-2aec5',
    storageBucket: 'flixflow-2aec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LrD2Sn8gLkXnzTPtRCpM0lRSKdzePAw',
    appId: '1:554364039576:ios:06be56e8c2fc2be17ffbed',
    messagingSenderId: '554364039576',
    projectId: 'flixflow-2aec5',
    storageBucket: 'flixflow-2aec5.appspot.com',
    iosBundleId: 'com.example.flixflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8LrD2Sn8gLkXnzTPtRCpM0lRSKdzePAw',
    appId: '1:554364039576:ios:06be56e8c2fc2be17ffbed',
    messagingSenderId: '554364039576',
    projectId: 'flixflow-2aec5',
    storageBucket: 'flixflow-2aec5.appspot.com',
    iosBundleId: 'com.example.flixflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCItoFFzQAibvYssohCZNY-hWwnj4i30XU',
    appId: '1:554364039576:web:6b37dade70b960d47ffbed',
    messagingSenderId: '554364039576',
    projectId: 'flixflow-2aec5',
    authDomain: 'flixflow-2aec5.firebaseapp.com',
    storageBucket: 'flixflow-2aec5.appspot.com',
    measurementId: 'G-R1WVSK8PEW',
  );
}
